### ISSUE TITLE
书籍勘误

### ISSUE THREAD

**Issue by diligence979** [react-book/book-code#5]
感谢大牛，我买了这本书，然后发现有几个地方貌似有误：

1. 【115页】
`document.body.innerYext = store.getState()` => `document.body.innerText = store.getState()`

2. 【133页】
`dispatch = compose(...chain, store.dispatch)` => `dispatch = compose(...chain)(store.dispatch)`

3. 【139页】
`方便地使用 Json.parse 等相关序列化方法` => `方便地使用 JSON.parse 等相关序列化方法`

**Comment by yanhaijing** [comment]
http://www.broadview.com.cn/book/5012
这里是书籍的勘误列表，可以看看是否重复，可以加微信 yanhaijing123

**Comment by diligence979** [comment]
好的~已经去提交了
